
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvouhsP9lTrtiJiuCg50xwSWNHuu-HCpg',
    authDomain: 'abdsh-8ef9d.firebaseapp.com',
    projectId: 'abdsh-8ef9d',
    storageBucket: 'abdsh-8ef9d.firebasestorage.app',
    messagingSenderId: '771285718310',
    appId: '1:771285718310:web:430ac3562203b92acb5de7',
    measurementId: 'G-PT93NXZNEC'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHirZF9rTj8SNRsV-2665hmRO4PB6u54',
    appId: '1:771285718310:android:4bd94901933f443acb5de7',
    messagingSenderId: '771285718310',
    projectId: 'abdsh-8ef9d',
    storageBucket: 'abdsh-8ef9d.firebasestorage.app'
  );
}
